// Lista fissa nell'ordine originale. `privateText` non viene mai restituito dal GET iniziale.
const raw = [
  ["Poison Kiss", "giochi", "Versione su tutto il corpo, non soltanto sul viso."],
  ["Più foto e video", "ricordi"],
  ["Un video di una giornata passata insieme", "ricordi"],
  ["Andare al mare (forse)", "uscite"],
  ["Farci foto col bacio vestiti fighi, e foto in generale", "ricordi"],
  ["Cucinare qualcosina, tipo crêpes o pancake", "cibo"],
  [null, "intimita", "La cosa col ghiaccio 👀"],
  [null, "intimita", "Usare il v, magari anche fuori"],
  ["Fare un dolce, magari non le crêpes", "cibo"],
  ["Comprarle un mazzo di fiori rossi, o anche solo rose", "gesti"],
  ["Giocare a Monopoly", "giochi", "Giocare a Monopoly in versione porno."],
  ["Guardare un film insieme che piace a Desy", "da-vedere"],
  ["Un secondo appuntamento", "uscite"],
  ["Ballare con la musica", "momenti"],
  [null, "intimita", "Fare la doccia insieme"],
  ["Lavare i denti insieme", "momenti"],
  ["Fare una foto mentre laviamo i denti insieme", "ricordi"],
  ["Fare la spesa insieme", "momenti"],
  [null, "intimita", "Fare il nostro gioco porno, ma dal vivo"],
  ["Far chiudere gli occhi all'altro e fargli indovinare dove gli si mette il dito sul proprio corpo", "giochi"],
  ["Provare a farle la colazione a letto", "gesti"],
  ["Farle un massaggio", "momenti", "Farle un massaggio sexy."],
  [null, "intimita", "Farci video e foto mentre lo facciamo"],
  ["Comprare un oggettino simbolico del nostro amore", "gesti"],
  ["Ascoltare la nostra canzone insieme", "momenti"],
  ["Vedere il video dei quattro anni insieme", "ricordi"],
  ["Scrivere otto parole e farle indovinare con soli venti indizi", "giochi"],
  ["Vince chi toglie per primo un calzino all'altro (?)", "giochi"],
  ["Guardare WALL·E", "da-vedere"],
  ["Prenderle dei girasoli", "gesti"],
  ["Farle vedere il mio mondo di Minecraft", "giochi"],
  ["Comprare le patatine classiche e i Kinder Bueno", "cibo"],
  ["Provare una piccola partita a un gioco di ruolo", "giochi"],
  ["Metterle l'eyeliner", "momenti"],
  ["Toglierle l'eyeliner (questo me lo hai detto tu di scriverlo ahaha)", "momenti"],
  [null, "intimita", "Farlo davanti allo specchio"],
  [null, "intimita", "Una giornata in cui sta tutto il giorno nuda"],
  ["Dire due parole insieme finché non diciamo la stessa", "giochi", null, "https://www.instagram.com/reel/DQ7apFPjazG"],
  ["Wolverine Nails Trend", "trend", null, "https://www.instagram.com/reel/DOQs7n8EzU7"],
  ["Appuntamento a Castel Gandolfo", "uscite"],
  ["Provare a farle guidare la macchina", "momenti"],
  ["Fare una storia su Instagram insieme (se si può)", "ricordi"],
  ["Scriverci addosso con l'UniPosca", "momenti"],
  ["Disegnarci il cerchio dietro l'orecchio", "gesti"],
  ["Fare delle foto di coppia", "ricordi"],
  ["Fare una foto a un cuore fatto con le nostre mani", "ricordi"],
  ["Whisper challenge", "giochi"],
  ["Un'idea vista su Instagram", "trend", null, "https://www.instagram.com/reel/DPO6EAdDX3G"],
  ["Provare a giocare a Little Nightmares", "giochi"],
  ["Preparare un jam heart toast", "cibo", null, "https://www.instagram.com/reel/DPgGK_UjaIw"],
  ["Andare su Uhmegle insieme, dove più o meno ci siamo conosciuti", "momenti"],
  ["Leggere insieme i messaggi salvati", "ricordi"],
  ["Stuck the cup, niente di che", "giochi", null, "https://youtube.com/shorts/XMCuFlKrbC8?si=xpCg-1BQtrbMTLmn"],
  ["Ascoltare le canzoni insieme", "momenti"],
  ["Andare in sala giochi", "uscite"],
  ["Andare al bowling", "uscite"],
  ["Andare a Roma", "uscite"],
  ["Andare al mare", "uscite"],
  ["Farle provare il selz limone e sale", "cibo"],
  ["Provare latte e menta", "cibo"],
  ["Gioco con le carte francesi: nero/rosso, sopra/sotto, dentro/fuori, segno", "giochi", null, "https://vm.tiktok.com/ZNRcwVEKj/"],
  ["Guardare il video di maggio insieme", "ricordi"],
  ["Leggere il messaggio d'amore più bello (e lungo) del mondo", "ricordi"],
  ["Andare nel Mondo Bianco", "momenti"],
  ["Vedere AoT insieme", "da-vedere"],
  ["Vedere Death Note insieme", "da-vedere"],
  ["Uno parla e l'altro, da dietro, fa le sue mani", "trend", null, "https://www.instagram.com/reel/DaNQq1UiW-v"],
  ["Giocare a nomi, cose e città con categorie strane", "giochi"],
  ["Festeggiare i nostri giorni di interazione su TikTok", "momenti"],
  ["Sfidarla ad aprirmi il pugno mentre lo stringo con forza", "giochi"],
  ["Tris con bottle flip e massimo tre segni in campo", "giochi", null, "https://vm.tiktok.com/ZN8J5jKtr/"],
  ["Il mimo al contrario", "giochi", null, "https://youtu.be/vFTMIFRzP54?is=kgcXW2szKsDAX6zm"],
  ["Giocare a Keep Talking and Nobody Explodes", "giochi"],
  ["Giocare a Spaceteam", "giochi"],
  ["Provare Party In", "giochi"],
  ["Mettere il profumo sugli elastici", "gesti"],
  ["Patatine in griglia 3×3 con tre punti bomba", "giochi", null, "https://vm.tiktok.com/ZN8Jghmud/"]
];

export const TOGETHER_ACTIVITIES = raw.map(([text, category, privateText = null, link = null], index) => ({
  id: index + 1,
  text,
  category,
  privateText,
  link,
  approximateMonth: null
}));

export function publicActivity(activity) {
  return {
    id: activity.id,
    text: activity.text,
    category: activity.category,
    link: activity.link,
    approximateMonth: activity.approximateMonth,
    hasPrivatePart: Boolean(activity.privateText),
    privateOnly: !activity.text
  };
}

