// Lista fissa nell'ordine originale. `privateText` non viene mai restituito dal GET iniziale.
const raw = [
  ["Poison Kiss: ognuno sceglie un posto su di sé che è velenoso, poi ci si dà bacini in giro e chi becca il punto velenoso perde", "giochi", "Si può fare anche in versione su tutto il corpo, non solo sul viso."],
  ["Più foto e video", "ricordi"],
  ["Un video tipo di una giornata che abbiamo passato insieme", "ricordi"],
  ["Andare al mare", "uscite"],
  ["Farci foto col bacio vestiti fighi e anche foto in generale", "ricordi"],
  ["Cucinare qualcosina (le crêpes/pancake)", "cibo"],
  [null, "intimita", "La cosa col ghiaccio 👀"],
  [null, "intimita", "Usare il v, magari anche fuori"],
  ["Fare un dolce, magari non le crêpes", "cibo"],
  ["Comprarle un mazzo di fiori rossi o anche solo rose", "gesti"],
  ["Giocare a Monopoly", "giochi", "Giocare a Monopoly in versione porno, oppure provare entrambe."],
  ["Guardare un film insieme che piace a Desy", "da-vedere"],
  ["Un secondo appuntamento", "uscite"],
  ["Ballare con la musica", "momenti"],
  [null, "intimita", "Fare la doccia insieme"],
  ["Lavare i denti insieme", "momenti"],
  ["Fare una foto mentre laviamo i denti insieme", "ricordi"],
  ["Fare la spesa insieme", "momenti"],
  [null, "intimita", "Fare il nostro gioco porno, ma dal vivo"],
  ["Far chiudere gli occhi all'altro e fargli indovinare dove gli si mette il dito sul proprio corpo", "giochi"],
  ["Provare a farle la colazione a letto", "gesti"],
  ["Farle un massaggio", "momenti", "Farle un massaggio sexy (boh)."],
  [null, "intimita", "Farci video e foto mentre lo facciamo"],
  ["Comprare un oggettino simbolico, per essere simbolo del nostro amore", "gesti"],
  ["Ascoltare la nostra canzone insieme", "momenti"],
  ["Vedere il video dei 4 anni insieme", "ricordi"],
  ["Gioco dove uno scrive 8 parole e l'altro deve indovinarle tutte avendo a disposizione solo 20 inizi (parole) che può dare l'altro", "giochi"],
  ["Vince chi toglie per primo un calzino all'altro (strano, ma l'ho trovato su internet)", "giochi"],
  ["Guardare WALL·E", "da-vedere"],
  ["Prenderle dei girasoli", "gesti"],
  ["Farle vedere il mio mondo di Minecraft (potrebbe essere una cosa dolce)", "giochi"],
  ["Comprare le patatine classiche e i Kinder Bueno", "cibo"],
  ["Provare a fare una piccola “partita” a un gioco di ruolo, per farglielo provare e conoscere e condividere una cosa mia", "giochi"],
  ["Metterle l'eyeliner", "momenti"],
  [null, "intimita", "Toglierle l'eyeliner (questo me lo hai detto tu di scriverlo ahaha)"],
  [null, "intimita", "Farlo davanti allo specchio"],
  [null, "intimita", "Una giornata in cui sta tutto il giorno nuda"],
  ["Il giochino di dire 2 parole insieme, fin quando non diciamo la stessa", "giochi", null, "https://www.instagram.com/reel/DQ7apFPjazG"],
  ["Wolverine Nails Trend", "trend", null, "https://www.instagram.com/reel/DOQs7n8EzU7"],
  ["Appuntamento a Castel Gandolfo", "uscite"],
  ["Provare a farle guidare la macchina", "momenti"],
  ["Fare una storia su Instagram insieme (se si può)", "ricordi"],
  [null, "intimita", "Scriverci addosso con l'UniPosca"],
  ["Disegnarci il cerchio dietro l'orecchio", "gesti"],
  ["Fare delle foto di coppia", "ricordi"],
  ["Fare una foto a un cuore fatto con le nostre mani", "ricordi"],
  ["Whisper challenge", "giochi"],
  [null, "removed", null, null, true],
  ["Provare a giocare a Little Nightmares", "giochi"],
  ["Preparare un jam heart toast", "cibo", null, "https://www.instagram.com/reel/DPgGK_UjaIw"],
  ["Andare su Uhmegle insieme (più o meno il posto dove ci siamo conosciuti)", "momenti"],
  ["Leggere insieme i messaggi salvati", "ricordi"],
  ["Stuck the cup (niente di che)", "giochi", null, "https://youtube.com/shorts/XMCuFlKrbC8?si=xpCg-1BQtrbMTLmn"],
  ["Ascoltare le canzoni insieme", "momenti"],
  ["Andare in sala giochi", "uscite"],
  ["Andare al bowling", "uscite"],
  ["Andare a Roma", "uscite"],
  ["Andare al mare", "uscite"],
  ["Farle provare il selz limone e sale", "cibo"],
  ["Provare latte e menta", "cibo"],
  ["Carte francesi: nero/rosso, sopra/sotto, dentro/fuori, segno", "giochi", null, "https://vm.tiktok.com/ZNRcwVEKj/"],
  ["Guardare il video di maggio insieme", "ricordi"],
  ["Leggere il messaggio d'amore più bello (e lungo) del mondo", "ricordi"],
  ["Andare nel Mondo Bianco", "momenti"],
  ["Vedere AoT insieme", "da-vedere"],
  ["Vedere Death Note insieme", "da-vedere"],
  ["Uno parla e l'altro è dietro e deve fare le mani dell'altro, magari preparando una cosa semplice", "trend", null, "https://www.instagram.com/reel/DaNQq1UiW-v"],
  ["Giocare a nomi, cose e città con categorie strane", "giochi"],
  ["Festeggiare i nostri giorni di interazione su TikTok", "momenti"],
  ["Sfidarla ad aprirmi il pugno mentre lo stringo con forza", "giochi"],
  ["Tris facendo il bottle flip, con solo 3 segni alla volta in campo", "giochi", null, "https://vm.tiktok.com/ZN8J5jKtr/"],
  ["Il mimo al contrario: uno dice cosa fare e chi mima deve indovinare cosa sta mimando", "giochi", null, "https://youtu.be/vFTMIFRzP54?is=kgcXW2szKsDAX6zm"],
  ["Giocare a Keep Talking and Nobody Explodes", "giochi"],
  ["Giocare a Spaceteam", "giochi"],
  ["Provare Party In", "giochi"],
  ["Mettere il profumo sugli elastici", "gesti"],
  ["La classica cosa delle patatine in una griglia 3×3, scegliendo 3 punti “bomba”", "giochi", null, "https://vm.tiktok.com/ZN8Jghmud/"],
  ["Giocare con la plastilina insieme", "giochi"]
];

export const TOGETHER_ACTIVITIES = raw
  .map(([text, category, privateText = null, link = null, removed = false], index) => ({
    id: index + 1,
    text,
    category,
    privateText,
    link,
    approximateDate: index + 1 <= 54 ? "OTT–DIC 2025" : index + 1 === 78 ? "LUG 2026" : "GEN–LUG 2026",
    removed
  }))
  .filter((activity) => !activity.removed);

export function publicActivity(activity) {
  return {
    id: activity.id,
    text: activity.text,
    category: activity.category,
    link: activity.link,
    approximateDate: activity.approximateDate,
    hasPrivatePart: Boolean(activity.privateText),
    privateOnly: !activity.text
  };
}
