-- Fase 4 del CMS (planning editor contenuti.md): prima fetta di migrazione, limitata alle
-- introduzioni testuali richieste dalla prima milestone. Tutte 'replace' (nessuna storia di
-- versioni preesistente da conservare) e created_by risolto dinamicamente sull'email di Rory,
-- così la migrazione resta valida sia in locale sia in remoto senza id hardcoded.
INSERT INTO content_entries (content_key, label, content_type, versioning_mode, body, created_by, created_at, updated_at)
SELECT v.content_key, v.label, v.content_type, 'replace', v.body, u.id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (
  SELECT 'mondo-bianco.benvenuta' AS content_key, 'Mondo Bianco — messaggio di benvenuto' AS label, 'plain_text' AS content_type, 'Benvenuta nel mondo bianco, ne hai sentito tanto parlare e forse ti sei chiesta cos''è e cosa intendessi dire ogni volta e finalmente eccoti qui, anche tu ci sei entrata. Forse ti ricordi com''è nato e forse no. Ma non ti preoccupare qui dentro c''è tutto quello che devi sapere su questo mondo e anche molto di più. Spero che per te sarà bello vederlo, quanto lo è stato per me farlo e sinceramente spero davvero che anche tu prenderai il tuo posto qui dentro e che questo possa essere e rimanere un luogo dove forse niente ha senso, ma per noi due si. Allora ti lascio esplorarlo e viverlo, spero che amerai perderti tra i suoi luoghi e le mie idee, e che magari questa diventerà una meta dove tornare, anche perché lo sai, ogni tanto ho aggiunto qualcosa in più. Buon viaggio' AS body
  UNION ALL
  SELECT 'ricettario.introduzione' AS content_key, 'Ricettario — introduzione' AS label, 'plain_text' AS content_type, 'La raccolta di tutte le ricette che abbiamo fatto insieme e di tutte quelle che vorremmo fare prima o poi.' AS body
  UNION ALL
  SELECT 'calendario.introduzione' AS content_key, 'Calendario — introduzione' AS label, 'plain_text' AS content_type, 'Mi piaceva l''idea che ci fosse un posto dove poter ricordare le nostre date importanti. (comunque hai notato che l''emoji del calendario ha il 17? 👀, non l''ho messo io è proprio così ahaha). Comunque spero che man mano ricorderò altre date belle importanti, purtroppo di tutto il nostro passato non ricordo tantissime cose, so che ce ne sono state tante, ma non ricordo quando. Tipo la prima volta che ci siamo detti ti amo, il giorno che abbiamo "inventato" il "noi", tutte le volte che ci siamo detti qualcosa di bellissimo senza nemmeno dargli troppa importanza, perché pensavamo che ce le saremmo detti per sempre. Per esempio mi ricordo che quando ti hanno rubato il telefono tu eri tanto triste perché c''erano tutti gli screen che ti eri fatta delle nostre chat. E mi dispiace che quegli screen non me li hai mai mandati, che appunto si sono persi così. Avrei voluto averli per ricordarli tutti. Quella volta ti avevo promesso che un giorno ci saremmo messi su ig a recuperare pian piano tutto. Ma non potevo farlo da solo e alla fine non lo abbiamo mai fatto. Ma quella promessa non l''ho mai dimenticata, come alla fine tante altre' AS body
  UNION ALL
  SELECT 'cose-insieme.introduzione' AS content_key, 'Agenda delle Idee — introduzione' AS label, 'plain_text' AS content_type, 'Finalmente puoi vedere anche tu la mia lista delle cose da fare insieme. Ho sempre lasciato tutto quello che ho scritto dall''inizio alla fine senza mai togliere niente, quindi ho deciso di portarla qui così com''era. Per questo si, ci sono cose che non si possono più "dire" e ci sono cose che non si possono più fare, ma in qualche modo hanno fatto parte della nostra storia di noi. Se vogliamo aggiungere cose, questa sarà la nostra lista e non più la mia' AS body
  UNION ALL
  SELECT 'lettere.introduzione' AS content_key, 'Cassetta delle Lettere — introduzione' AS label, 'plain_text' AS content_type, 'Un tempo era un posto pensato per lasciarmi foto e video come ricordo, adesso invece può essere quello che è sempre stato: una cassetta dove lasciare pensieri e letterine che rimarranno raccolti qui.' AS body
) v
JOIN users u ON u.email = 'rory982011@gmail.com';
