-- Migrazione manuale: porta in produzione i contenuti editati in locale
-- (ricette, testi introduttivi, descrizioni card, paragrafi Mappa, GDR,
-- riordinamenti). Esclude di proposito world_settings (preferenze live
-- reali sul sito, non vanno sovrascritte), carte_definizioni (non ancora
-- finalizzate), letters/pensieri_biglietti (dati di test).

-- recipes: sostituzione completa (16 righe, tutte modificate o nuove)
DELETE FROM recipes;
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('pizza-pane', 'Impasto per pane (ma ci si può fare anche la pizza)', 'Fatta insieme', NULL, 0, NULL, NULL, '["375 g di farina 00/0","125 g di semola rimacinata o grano duro","300 ml di acqua","7–8 g di lievito fresco","10 g di sale","10 g di olio"]', '["Mettere le farine e il sale in una ciotola e mescolare a secco","Fare sciogliere il lievito in acqua tiepida (non calda)","Impastare aggiungendo acqua e olio pian piano fin quando il composto è omogeneo e senza grumi","Creare con le mani facendo le pieghe un pallona di impasto (sculacciare con vigore alla fine)","Le pieghe sono importanti per formare la maglia glutinica","Far lievitare per 2 ore","Dividere l’impasto in palline più piccole, fare di nuovo le pieghe e chiudere sotto la palla (sculacciare di nuovo alla fine)","Far lievitare i panetti per altre 2 ore","Per Pizza:","Stendere l''impasto su una teglia con un po'' di farina sotto per non fare attaccare","Condire a piacere","Cuocere la pizza a 240–250 °C, per circa 10–15 minuti","Per Pane:","Cuocere il pane a 180–200 °C per circa 20 minuti, controllando la doratura"]', 7, 1, '2026-08-12 15:06:56', '2026-08-15T10:19:58.363Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('pasta-uovo', 'Pasta all’uovo', 'Fatta insieme', NULL, 0, NULL, NULL, '["200 g di farina 00","2 uova","1 pizzico di sale"]', '["Impastare farina, uova e sale","Far riposare il panetto per 30 minuti","Stendere l’impasto col tubo/mattarello","Tagliarlo al coltello per ottenere tagliatelle o pappardelle rustiche","Cuocere in acqua salata per 2–4 minuti","Scolare e condire a piacere"]', 8, 1, '2026-08-12 15:06:56', '2026-08-15T10:19:56.355Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('ragu-bianco', 'Ragù bianco semplice', 'Fatta insieme', NULL, 0, NULL, NULL, '["200–250 g di macinato misto (maiale e bovino)","Soffritto pronto","Olio","Sale e pepe","Vino bianco","Rosmarino o salvia (facoltativi)","Latte (facoltativo)"]', '["Scaldare l’olio col soffritto","Aggiungere la carne e rosolarla bene","Sfumare con il vino bianco","Aggiungere sale, pepe e se ci sono rosmarino e salvia","Cuocere a fuoco lento per 30/40 minuti","Per creare una cremina o se ha un sapore troppo alcolico alla fine aggiungere un goccio di latte se serve","Mettere in una padella il ragù con la pasta e un po'' di acqua di cottura e mantecare"]', 9, 1, '2026-08-12 15:06:56', '2026-08-15T10:17:45.581Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('cookies', 'Cookies (circa 12)', 'Fatta insieme', NULL, 0, NULL, NULL, '["190 g di farina 00","115 g di burro morbido","150 g di gocce di cioccolato fondente","1 uovo medio","65 g di zucchero di canna","65 g di zucchero bianco","4 g di lievito per dolci vanigliato","1 pizzico di sale"]', '["Mettere gli zuccheri in una ciotola e mescolare a secco","Unire il burro","Aggiungere l’uovo","Unire farina, lievito e sale","Aggiungere le gocce di cioccolato","Lasciare l’impasto in frigo per 30 minuti con della pellicola a tappare la ciotola","Formare circa 12 palline e metterle nella teglia a forma di pallina","Cuocere in forno statico a 165 °C per 18/22 minuti","Controllare che i biscotti si \"schiaccino\" e dopo che si dorino un po''. Devono rimanere morbidi dentro e croccanti fuori","Lasciare raffreddare dopo averli usciti dal forno per almeno 15/20 minuti"]', 10, 1, '2026-08-12 15:06:56', '2026-08-15T10:17:42.283Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('patate-schiacciate', 'Patate schiacciate croccanti', 'Da provare', NULL, 0, NULL, NULL, '["Patate piccole o medie", "Olio", "Sale e pepe", "Rosmarino o paprika", "Parmigiano, facoltativo", "Salsa yogurt, maionese o ketchup, facoltativi"]', '["Bollire le patate finché diventano morbide.", "Disporle sulla carta forno.", "Schiacciarle con un bicchiere.", "Condire con olio, sale, pepe e rosmarino o paprika.", "Cuocere a 220 °C finché diventano croccanti."]', 13, 1, '2026-08-12 15:06:56', '2026-08-15T10:17:33.949Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('crepes', 'Crêpes', 'Da provare', NULL, 0, NULL, NULL, '["3 uova medie", "250 g di farina 00", "500 g di latte intero", "40 g di burro"]', '["Mescolare uova e latte.", "Aggiungere la farina poco alla volta.", "Unire il burro fuso.", "Far riposare la pastella, se possibile.", "Cuocere in una padella calda leggermente imburrata."]', 14, 1, '2026-08-12 15:06:56', '2026-08-15T10:17:30.620Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('pollo-curry', 'Pollo al curry', 'Fatta insieme', NULL, 1, NULL, NULL, '["300 g di petto di pollo","Farina","Acqua","Latte (facoltativo)","Curry","Olio"]', '["Tagliare il pollo a cubetti della dimensione che piace, preferibilmente un pezzo entri in bocca","Passare ogni pezzo di pollo nella farina in modo che si attacchi","Mettere un po'' d''olio in padella e soffriggere il pollo fin quando non è leggermente dorato e la farina è sigillata","Aggiungere l''acqua e il curry (abbondante)","Far cuocere a fuoco lento per almeno 15 minuti per cuocere il pollo","Lasciare evaporare l''acqua per far stringere il sugo e renderlo cremoso","Se necessario o preferito aggiungere un po'' di latte per rendere il composto ancora più cremoso"]', 2, 1, '2026-08-12 15:06:56', '2026-08-15T10:20:27.938Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('biscotti-pasta-frolla', 'Biscotti di pasta frolla', 'Fatta insieme', NULL, 0, NULL, NULL, '["250 g farina 00","125 g burro freddo","100 g zucchero","1 uovo medio","Mezza bustina di lievito per dolci","1 pizzico di sale"]', '["Setacciare la farina con il lievito e aggiungere il burro a cubetti","Impastare con le mani finché il composto diventa friabile e il burro non è più visibile","Incorporare zucchero, sale e uovo, mescolando prima con una forchetta","Lavorare bene con le mani fino a ottenere un composto liscio e omogeneo","Formare una palla, avvolgere in pellicola e riporre in frigo per 30 minuti","Stendere l''impasto con il mattarello su carta da forno infarinata a uno spessore di circa 3 mm (o come viene insomma)","Ricavare le forme desiderate (rigorosamente a caso col coltello e fare cose tipo stelle storte)","Disporre su teglia con carta da forno e cuocere a 170°C per circa 12 minuti, finché non sono appena dorati","Lasciare raffreddare prima di staccare i biscotti dalla teglia"]', 3, 1, '2026-08-12 15:06:56', '2026-08-15T10:20:27.938Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('latte-menta', 'Latte e menta', 'Da provare', NULL, 0, NULL, NULL, '["Latte freddo", "Sciroppo alla menta"]', '["Versare il latte in un bicchiere.", "Aggiungere poco sciroppo alla menta alla volta.", "Mescolare e fermarsi quando il sapore ci piace."]', 15, 1, '2026-08-12 15:06:56', '2026-08-15T10:17:29.287Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('selz-limone-sale', 'Selz, limone e sale', 'Da provare', NULL, 0, NULL, NULL, '["Acqua di selz molto fredda (va bene l''acqua frizzante)","Succo di limone","Un pizzico di sale"]', '["Versare il succo di limone nel bicchiere","Aggiungere il selz o l''acqua","Completare aggiungendo il sale e mescolare energicamente"]', 16, 1, '2026-08-12 15:06:56', '2026-08-15T10:17:27.191Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('salsiccia-patate', 'Salsiccia e patate', 'Fatta insieme', 'La nostra prima ricetta fatta insieme.', 0, NULL, NULL, '["Salsiccia","Patate","Olio","Sale","Pepe (se vuoi)"]', '["Se è troppo spessa, togliere la pelle alla salsiccia e tagliarla a pezzettini.","Tagliare le patate a cubetti (mi raccomando metti bene le mani 👀)","Mettere tutto in una teglia","Creare una laghetto di olio (circa 22 litri) nella teglia","Infornarle a 200 °C.","Cuocere per circa 20 minuti o finché le patate non sono morbide e la salsiccia dorata","Se necessario eliminare un po'' di olio durante la cottura (a causa del lago fatto prima)"]', 0, 1, '2026-08-12 15:06:56', '2026-08-15T09:13:51.614Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('trofie-pesto', 'Trofie col pesto del barattolo', 'Fatta insieme', 'Ricetta super gourmet', 0, NULL, NULL, '["Trofie (rigorosamente a caso)","Pesto del barattolo","Sale"]', '["Fare bollire l''acqua col sale","Buttare la pasta","Scolare la pasta","Mettere la pasta e il pesto del baratto in una padella e fare mantecare","Servire :)"]', 5, 1, '2026-08-12 15:06:56', '2026-08-15T10:20:07.801Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('pasta-passata-pizza', 'Pasta con la passata rimasta dalla pizza', 'Fatta insieme', 'Visto che non si butta niente qui', 0, NULL, NULL, '["Pasta","La passata avanzata dalla pizza (solo quella non si può fare altro)","Olio","Zucchero (se necessario)","Sale"]', '["Mettere la passata avanzata in padella e farla stringere con un po'' d''olio","Se la passata risulta troppo acida, aggiungere un pizzico di zucchero","Salare per la sapidità","Scolare la pasta e metterla in padella con tantissimo sugo, molto più del necessario e farla mantecare","Mangiarla ricordando che un tempo era una pizza"]', 11, 1, '2026-08-12 15:06:56', '2026-08-15T10:17:39.718Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('dolce-di-desy', 'Dolce di Desy', 'Fatta insieme', 'Dovresti aggiungere la tua ricetta del tuo dolce, che ti è stranamente venuto benissimo (ovvio c''ero io con te u.u)', 1, NULL, NULL, '["Non me li ricordo","Però c''è il kefir scaduto mi pare"]', '["Non lo so"]', 4, 1, '2026-08-15T09:46:54.006Z', '2026-08-15T10:20:18.431Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('fusilli-tonno-zucchine', 'Fusilli con Tonno e Zucchine Spappolate (Già pronto)', 'Fatta insieme', NULL, 0, NULL, NULL, '["Fusilli (a caso ovvio)","Sugo tonno e zucchine preparato da tua mamma (buono, lo ammetto)"]', '["Far cuocere in acqua bollente e salata i fusilli","Scolare la pasta e metterla in padella con il sugo del barattolo","Fare mantecare e servire","Facile e veloce, se qualcuno ha già fatto il lavoro sporco per te 👀"]', 6, 1, '2026-08-15T10:14:15.123Z', '2026-08-15T10:20:04.071Z');
INSERT INTO recipes (id, title, kind, note, placeholder, source_label, source_href, ingredients, steps, position, created_by, created_at, updated_at) VALUES ('iced-coffee', 'Iced Coffee', 'Fatta insieme', NULL, 0, NULL, NULL, '["Ghiaccio","Caffè","Latte","Dolcificante"]', '["Fare il caffè","Mettere il ghiaccio in un bicchiere","Diluire con il latte fino all''orlo","Aggiungere un numero indefinito e sempre diverso per ogni porzione, di goccine di dolcificante","Mescolare e servire"]', 1, 1, '2026-08-15T10:17:19.238Z', '2026-08-15T10:20:24.065Z');

UPDATE content_entries SET body = 'Hai presente quei video di TikTok o IG dove il ragazzo chiede cose alla ragazza tramite un sito creato da lui, ma c''è sempre qualcosa che non va con i bottoni ahaha? Ho visto che ti sembrano carini, quindi beh ecco a te! E mi raccomando, rispondi sinceramente 👀 ahaha' WHERE content_key = 'prova-a-dire-no.introduzione';
UPDATE content_entries SET body = 'La raccolta di tutte le ricette che abbiamo fatto insieme e di tutte quelle che vorremmo fare prima o poi. Quando dico tutte, intendo proprio tutte' WHERE content_key = 'ricettario.introduzione';

UPDATE content_versions SET body = 'Giusto per fartelo sapere, questa è la cosa che ho aggiunto dopo. Lo sai che ho sempre pensato che mi piacerebbe farti provare i giochi di ruolo no? Perché beh trovo quasi assurdo il fatto che proprio tu non sia mai entrata per niente a far parte di una della mie passioni più grandi. Quindi ho pensato che volevo trovare un modo per fartelo provare e allo stesso tempo un modo per giocare un pochino insieme, visto che non possiamo più farlo come prima. E questo è l''unico modo carino che mi è venuto in mente ahaha. Quindi beh spero che ti piaccia l''idea e che ti divertirai

Beh come funziona? Ho creato dei piccoli sistemi super semplificati, super semplici, super veloci e super un sacco di cose ahaha. Così non devi imparare una marea di regole (per ora 👀) e puoi provare solo la parte bella di giocare e possiamo giocare insieme. Io ti faccio da master e ho già creato delle storie per te, dove tu ovviamente sei la protagonista e ricordati che puoi fare tutto quello che vuoi, il personaggio è tuo e lo muovi come vuoi. Ovviamente puoi chiedermi delucidazioni se hai dei dubbi

All''interno delle avventure ci sono le regole nella schedina in basso, basta aprirla. Mentre invece come facciamo a giocare? Anche questo è molto semplice. Mi sono ispirato a una cosa che alcuni fanno nei forum, che io non ho mai fatto quindi la proviamo insieme ahaha. Ovvero una cosa che si chiama "play-by-chat", appunto si gioca tramite la chat. Cioè che io scrivo qualcosa sul come prosegue la tua avventura e poi aspetto la tua risposta. Tendenzialmente cercherò sempre di lasciarti sempre con una domanda o delle scelte e tu descriverai cosa fa/dice il tuo personaggio (es: Patrizia esclama "oh mio dio" e corre verso la strada a sinistra) e poi io ti rispondo, e si va avanti così fino alla fine della storia. Beh questo è tutto, molto semplice. Obiettivo in generale non è "vincere" qualcosa, ma solo raccontare una storia insieme e divertirci giocando

Bene, adesso che sai tutto direi che siamo pronti! Quindi beh, non ti resta che sceglierne una e leggere la prima parte della storia e fare la tua prima mossa ahaha. Beh spero proprio buon divertimento allora! Dai, ormai ho fatto tutto, tanto vale provare 👀' WHERE id = 8;

UPDATE gdr_blocks SET position = 40 WHERE id = 40;
UPDATE gdr_blocks SET position = 41 WHERE id = 41;

UPDATE linguaggio_segreto_symbols SET position = 2 WHERE id = 25;

UPDATE map_destinations SET paragraphs = '["Da quando a Maggio mi hai detto che vuoi visitare Roma insieme a me, quella cosa mi è rimasta dentro sai? Io ci avevo sempre pensato che sarebbe stato molto bello visitarla con te e sinceramente se l''unica persona con cui vorrei visitare Roma, altrimenti penserei solo a te ahaha. Sai? Quando dico che ci ho sempre pensato, intendo sempre ahaha, mi sarebbe piaciuto andarci pure a Settembre poi con i problemi della macchina non abbiamo potuto. In più ho sempre avuto \"paura\" che per te andare a Roma fosse una cosa \"banale\" e che non fosse speciale come magari lo poteva essere per me, visto che tu ce l''hai a due passi più o meno ahaha. Ma alla fine ho capito che non era così, e quindi spererò sempre di poter vedere il Colosseo o la Fontana di Trevi insieme a te"]' WHERE id = 'roma';
UPDATE map_destinations SET paragraphs = '["Come non potrei mettere \"casa\" mia? Dico da sempre che odio la Sicilia, perché sento che il fatto che abito in questo posto, mi ha da sempre tolto troppe possibilità, e tu per esempio sei stata una di queste, ma una cosa buona gliela devo riconoscere: è bellissima e ci sono posti che vale la pena andare a vedere e questi sono alcuni dei più belli, che mi hanno colpito e che vorrei tanto visitare insieme a te un giorno","Questo è un posto che forse dal vivo non sarà niente di che, ma dalla prima volta che l''ho visto ci ho sempre sentito un pizzico di magia. È un piccolissimo fiumiciattolo che si chiama Amenano che scorre sotto terra a Catania, che si trova in questa piccola grotta, sotto quello che ora è un ostello. Tra l''altro in questa grotta si può cenare ahaha. Anche la storia è affascinante, magari un giorno te la racconterò mentre siamo lì davanti","Forse ti ricordi che amo i posti molto naturali, e questo è uno di quelli che mi ha sempre affascinato. Ci sono stato poche volte nella mia vita, ma mi è rimasto dentro. Le Gole dell''Alcantara. C''è un piccolo fiume che esce da appunto delle gole, queste \"montagne\" molto alte e proprio perché passa così tanto tempo tra le rocce e all''ombra, l''acqua è letteralmente quasi congelata. Si può fare il bagno e dopo il trauma del freddo ci si abitua un po'' ed è piacevole ahaha","Questo forse è il posto più bello in cui io sia mai stato. Almeno lo ricordo così, perché ci sono stato solo una volta se non mi sbaglio quando ero piccolo. Sono i laghetti di Cava Grande ad Avola, e sono appunto dei piccoli laghi all''interno di un canyon, quindi totalmente nella natura e l''acqua è calma e pulitissima. Sembra davvero un posto magico. L''unica pecca è che per arrivarci ci sono solo delle scale e sono tipo 40 minuti di scalinate prima di arrivare alla terra promessa ahaha. È molto faticoso, ma alla fine ripaga tutto e forse anche per questo è un posto così speciale, non è semplice da raggiungere e quindi può goderselo solo chi riesce ad affrontare il percorso","Forse avrai sentito parlare dell''Isola Bella, è appunto un''isoletta piccola e piena di verde che si trova proprio davanti a una spiaggia a Taormina. Sono stato decine di volte in quella spiaggia, ma credo di non essere mai entro nell''isola. Sarebbe molto bello farlo insieme a te un giorno"]', images = '[{"src":"../assets/images/world/map/sicilia-catania.webp","alt":"Il fiume Amenano nella grotta sotto l''ostello","beforeParagraph":1},{"src":"../assets/images/world/map/sicilia-alcantara.webp","alt":"Le Gole dell''Alcantara","beforeParagraph":2},{"src":"../assets/images/world/map/sicilia-avola.webp","alt":"I laghetti di Cava Grande ad Avola","beforeParagraph":3},{"src":"../assets/images/world/map/sicilia-taormina.webp","alt":"Isola Bella a Taormina","beforeParagraph":4}]' WHERE id = 'sicilia';

UPDATE stories SET position = 4 WHERE id = 'il-lento';
UPDATE stories SET position = 3 WHERE id = 'il-magico-campo-d-erba';

